# This configuration file should FAIL to load because it has
# duplicate server blocks on the same port with the same server_name

server {
	listen 8080;
	server_name localhost;
	root www;
	index index.html;

	location / {
		root www;
		methods GET;
	}
}

server {
	listen 8080;
	server_name localhost;
	root www;
	index index.html;

	location / {
		root www;
		methods GET;
	}
}
